"""Canonical enums from the approved PHASE 2 specification."""

from enum import StrEnum, unique


@unique
class Timeframe(StrEnum):
    M5 = "5m"
    M15 = "15m"
    H1 = "1h"


@unique
class MarketRegime(StrEnum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    SIDEWAY = "SIDEWAY"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    UNCERTAIN = "UNCERTAIN"


@unique
class TradeDecision(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"


@unique
class TradeSide(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


@unique
class RiskAction(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    HALT = "HALT"


@unique
class BotState(StrEnum):
    STARTING = "STARTING"
    SYNCING = "SYNCING"
    OBSERVING = "OBSERVING"
    EVALUATING = "EVALUATING"
    SUBMITTING = "SUBMITTING"
    PENDING_ENTRY = "PENDING_ENTRY"
    MANAGING_POSITION = "MANAGING_POSITION"
    EXITING = "EXITING"
    COOLDOWN = "COOLDOWN"
    RECOVERING = "RECOVERING"
    HALTED = "HALTED"


@unique
class TradeLifecycleState(StrEnum):
    CANDIDATE_CREATED = "CANDIDATE_CREATED"
    RISK_REVIEW = "RISK_REVIEW"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    SUBMITTING = "SUBMITTING"
    PENDING_ENTRY = "PENDING_ENTRY"
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    RECOVERY = "RECOVERY"
    HALTED = "HALTED"


@unique
class TradeLifecycleEvent(StrEnum):
    RISK_REVIEW_STARTED = "RISK_REVIEW_STARTED"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_HALT = "RISK_HALT"
    ORDER_INTENT_PERSISTED = "ORDER_INTENT_PERSISTED"
    ORDER_ACKNOWLEDGED = "ORDER_ACKNOWLEDGED"
    ORDER_REJECTED = "ORDER_REJECTED"
    SUBMIT_OUTCOME_UNKNOWN = "SUBMIT_OUTCOME_UNKNOWN"
    ENTRY_CANCELED_UNFILLED = "ENTRY_CANCELED_UNFILLED"
    ENTRY_FILLED_PROTECTED = "ENTRY_FILLED_PROTECTED"
    PARTIAL_FILL = "PARTIAL_FILL"
    TAKE_PROFIT_FAILED = "TAKE_PROFIT_FAILED"
    EXIT_TRIGGERED = "EXIT_TRIGGERED"
    STATE_UNCERTAIN = "STATE_UNCERTAIN"
    PROTECTION_FAILED = "PROTECTION_FAILED"
    POSITION_CLOSED = "POSITION_CLOSED"
    EXIT_OUTCOME_UNKNOWN = "EXIT_OUTCOME_UNKNOWN"
    RECONCILED_NO_FILL = "RECONCILED_NO_FILL"
    RECONCILED_PENDING_ORDER = "RECONCILED_PENDING_ORDER"
    RECONCILED_PROTECTED_POSITION = "RECONCILED_PROTECTED_POSITION"
    RECONCILED_CLOSED = "RECONCILED_CLOSED"
    RECOVERY_FAILED = "RECOVERY_FAILED"


@unique
class BotEvent(StrEnum):
    CONFIG_VALIDATED = "CONFIG_VALIDATED"
    STARTUP_VALIDATION_FAILED = "STARTUP_VALIDATION_FAILED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    SYNC_FAILED = "SYNC_FAILED"
    CANDLE_CLOSED = "CANDLE_CLOSED"
    LOSS_COOLDOWN_STARTED = "LOSS_COOLDOWN_STARTED"
    HEALTH_CRITICAL = "HEALTH_CRITICAL"
    NO_TRADE = "NO_TRADE"
    RISK_REJECTED = "RISK_REJECTED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_HALT = "RISK_HALT"
    ORDER_ACKNOWLEDGED = "ORDER_ACKNOWLEDGED"
    ORDER_REJECTED = "ORDER_REJECTED"
    SUBMIT_OUTCOME_UNKNOWN = "SUBMIT_OUTCOME_UNKNOWN"
    ENTRY_CANCELED_UNFILLED = "ENTRY_CANCELED_UNFILLED"
    ENTRY_FILLED_PROTECTED = "ENTRY_FILLED_PROTECTED"
    PARTIAL_FILL_OR_PROTECTION_UNKNOWN = "PARTIAL_FILL_OR_PROTECTION_UNKNOWN"
    EXIT_TRIGGERED = "EXIT_TRIGGERED"
    STATE_UNCERTAIN = "STATE_UNCERTAIN"
    PROTECTION_FAILED = "PROTECTION_FAILED"
    POSITION_CLOSED = "POSITION_CLOSED"
    EXIT_OUTCOME_UNKNOWN = "EXIT_OUTCOME_UNKNOWN"
    RECONCILED_FLAT = "RECONCILED_FLAT"
    RECONCILED_PROTECTED_POSITION = "RECONCILED_PROTECTED_POSITION"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    COOLDOWN_EXPIRED = "COOLDOWN_EXPIRED"
    RISK_REDUCING_ACTION = "RISK_REDUCING_ACTION"
    OPERATOR_RESET_REQUESTED = "OPERATOR_RESET_REQUESTED"


@unique
class RangeLocation(StrEnum):
    NEAR_SUPPORT = "NEAR_SUPPORT"
    MIDDLE = "MIDDLE"
    NEAR_RESISTANCE = "NEAR_RESISTANCE"
    OUTSIDE_RANGE = "OUTSIDE_RANGE"


@unique
class BreakoutState(StrEnum):
    NONE = "NONE"
    BREAKOUT_DETECTED = "BREAKOUT_DETECTED"
    WAIT_CONFIRMATION = "WAIT_CONFIRMATION"
    WAIT_RETEST = "WAIT_RETEST"
    RETEST_VALIDATED = "RETEST_VALIDATED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"


@unique
class BreakoutDirection(StrEnum):
    UP = "UP"
    DOWN = "DOWN"


@unique
class LevelKind(StrEnum):
    SUPPORT = "SUPPORT"
    RESISTANCE = "RESISTANCE"
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"
    RANGE_BOUNDARY = "RANGE_BOUNDARY"


@unique
class LevelMethod(StrEnum):
    SWING_CLUSTER = "SWING_CLUSTER"
    VOLUME_REACTION = "VOLUME_REACTION"
    MARKET_STRUCTURE = "MARKET_STRUCTURE"
    RANGE_MODEL = "RANGE_MODEL"


@unique
class StructureTrend(StrEnum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    MIXED = "MIXED"
    UNDETERMINED = "UNDETERMINED"


@unique
class StructurePointKind(StrEnum):
    HH = "HH"
    HL = "HL"
    LH = "LH"
    LL = "LL"
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"


@unique
class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


@unique
class HealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    UNKNOWN = "UNKNOWN"


@unique
class OrderStatus(StrEnum):
    INTENT_CREATED = "INTENT_CREATED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


@unique
class PositionStatus(StrEnum):
    FLAT = "FLAT"
    OPENING = "OPENING"
    OPEN = "OPEN"
    CLOSING = "CLOSING"
    CLOSED = "CLOSED"
    UNRECONCILED = "UNRECONCILED"


@unique
class ExitReason(StrEnum):
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT = "TAKE_PROFIT"
    RISK_REDUCTION = "RISK_REDUCTION"
    EMERGENCY = "EMERGENCY"
    MANUAL = "MANUAL"
    UNKNOWN = "UNKNOWN"


@unique
class LiquidityRole(StrEnum):
    MAKER = "MAKER"
    TAKER = "TAKER"
    UNKNOWN = "UNKNOWN"


@unique
class OrderPurpose(StrEnum):
    ENTRY = "ENTRY"
    STOP = "STOP"
    TAKE_PROFIT = "TAKE_PROFIT"
    EXIT = "EXIT"


@unique
class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_MARKET = "STOP_MARKET"
    TAKE_PROFIT_MARKET = "TAKE_PROFIT_MARKET"


@unique
class OrderDirection(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


@unique
class SignalComponentName(StrEnum):
    TREND = "TREND"
    MOMENTUM = "MOMENTUM"
    STRUCTURE = "STRUCTURE"
    LEVEL = "LEVEL"
    VOLUME = "VOLUME"
    CONFIRMATION = "CONFIRMATION"


@unique
class SetupType(StrEnum):
    TREND_PULLBACK = "TREND_PULLBACK"
    SIDEWAY_MEAN_REVERSION = "SIDEWAY_MEAN_REVERSION"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"


@unique
class EntryModel(StrEnum):
    CLOSE_REFERENCE = "CLOSE_REFERENCE"


@unique
class TargetModel(StrEnum):
    NEXT_OPPOSING_LEVEL = "NEXT_OPPOSING_LEVEL"


@unique
class PositionMode(StrEnum):
    NET = "NET"
    LONG_SHORT = "LONG_SHORT"


@unique
class MarginMode(StrEnum):
    ISOLATED = "ISOLATED"
    CROSS = "CROSS"


@unique
class GapPolicy(StrEnum):
    BLOCK_AND_BACKFILL = "BLOCK_AND_BACKFILL"


@unique
class PartialFillPolicy(StrEnum):
    PROTECT_FILLED_AND_CANCEL_REMAINDER = "PROTECT_FILLED_AND_CANCEL_REMAINDER"


@unique
class ProtectionFailurePolicy(StrEnum):
    CANCEL_REMAINDER_REDUCE_AND_HALT = "CANCEL_REMAINDER_REDUCE_AND_HALT"


@unique
class TakeProfitFailurePolicy(StrEnum):
    RECOVER_THEN_REDUCE_AND_HALT = "RECOVER_THEN_REDUCE_AND_HALT"


@unique
class JournalBackend(StrEnum):
    SQLITE = "SQLITE"


@unique
class SmoothingMethod(StrEnum):
    WILDER = "WILDER"


@unique
class VolumeStatistic(StrEnum):
    MEAN = "MEAN"


@unique
class DecimalRoundingMode(StrEnum):
    ROUND_HALF_EVEN = "ROUND_HALF_EVEN"


@unique
class ExecutionEnvironment(StrEnum):
    BACKTEST = "BACKTEST"
    DEMO = "DEMO"
    LIVE = "LIVE"


@unique
class JournalEventType(StrEnum):
    DECISION_EVALUATED = "DECISION_EVALUATED"
    RISK_EVALUATED = "RISK_EVALUATED"
    ORDER_INTENT_CREATED = "ORDER_INTENT_CREATED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_ACKNOWLEDGED = "ORDER_ACKNOWLEDGED"
    FILL_RECEIVED = "FILL_RECEIVED"
    PROTECTION_CONFIRMED = "PROTECTION_CONFIRMED"
    POSITION_UPDATED = "POSITION_UPDATED"
    EXIT_COMPLETED = "EXIT_COMPLETED"
    RECONCILIATION = "RECONCILIATION"
    DATA_CORRECTION = "DATA_CORRECTION"
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    INVALID_TRANSITION = "INVALID_TRANSITION"


@unique
class ReasonCode(StrEnum):
    DATA_MISSING = "DATA_MISSING"
    CANDLE_INVALID = "CANDLE_INVALID"
    DATA_STALE = "DATA_STALE"
    DATA_GAP = "DATA_GAP"
    DATA_DUPLICATE = "DATA_DUPLICATE"
    DATA_CONFLICT = "DATA_CONFLICT"
    DATA_OUT_OF_ORDER = "DATA_OUT_OF_ORDER"
    TIMEFRAME_UNSYNCED = "TIMEFRAME_UNSYNCED"
    CLOCK_DRIFT = "CLOCK_DRIFT"
    DATA_UNHEALTHY = "DATA_UNHEALTHY"
    INDICATOR_NOT_READY = "INDICATOR_NOT_READY"
    INDICATOR_INVALID = "INDICATOR_INVALID"
    REGIME_UNCERTAIN = "REGIME_UNCERTAIN"
    HIGH_VOLATILITY_BLOCKED = "HIGH_VOLATILITY_BLOCKED"
    REGIME_DIRECTION_BLOCKED = "REGIME_DIRECTION_BLOCKED"
    RANGE_INVALID = "RANGE_INVALID"
    RANGE_STALE = "RANGE_STALE"
    SIDEWAY_MIDDLE_RANGE = "SIDEWAY_MIDDLE_RANGE"
    SETUP_DISABLED = "SETUP_DISABLED"
    NO_CONFIRMATION = "NO_CONFIRMATION"
    BREAKOUT_CONFIRMATION_PENDING = "BREAKOUT_CONFIRMATION_PENDING"
    BREAKOUT_INVALIDATED = "BREAKOUT_INVALIDATED"
    RETEST_PENDING = "RETEST_PENDING"
    RETEST_INVALIDATED = "RETEST_INVALIDATED"
    RETEST_EXPIRED = "RETEST_EXPIRED"
    SCORE_TOO_LOW = "SCORE_TOO_LOW"
    NO_SIGNAL = "NO_SIGNAL"
    CONFLUENCE_TOO_LOW = "CONFLUENCE_TOO_LOW"
    SCORE_DIFFERENCE_TOO_SMALL = "SCORE_DIFFERENCE_TOO_SMALL"
    AMBIGUOUS_SIGNAL = "AMBIGUOUS_SIGNAL"
    SIGNAL_INVALID = "SIGNAL_INVALID"
    INVALID_STOP = "INVALID_STOP"
    INVALID_ENTRY_PRICE = "INVALID_ENTRY_PRICE"
    STOP_TOO_CLOSE = "STOP_TOO_CLOSE"
    STOP_TOO_FAR = "STOP_TOO_FAR"
    TARGET_INVALID = "TARGET_INVALID"
    LEVEL_TOO_CLOSE = "LEVEL_TOO_CLOSE"
    RR_TOO_LOW = "RR_TOO_LOW"
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    DAILY_DRAWDOWN_LIMIT = "DAILY_DRAWDOWN_LIMIT"
    DAILY_TRADE_LIMIT = "DAILY_TRADE_LIMIT"
    CONSECUTIVE_LOSS_LIMIT = "CONSECUTIVE_LOSS_LIMIT"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    RISK_BUDGET_INVALID = "RISK_BUDGET_INVALID"
    RISK_BUDGET_EXCEEDED = "RISK_BUDGET_EXCEEDED"
    POSITION_SIZE_TOO_SMALL = "POSITION_SIZE_TOO_SMALL"
    POSITION_CAP_EXCEEDED = "POSITION_CAP_EXCEEDED"
    LEVERAGE_CAP_EXCEEDED = "LEVERAGE_CAP_EXCEEDED"
    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN"
    INSTRUMENT_METADATA_STALE = "INSTRUMENT_METADATA_STALE"
    INSTRUMENT_UNSUPPORTED = "INSTRUMENT_UNSUPPORTED"
    NUMERICAL_ERROR = "NUMERICAL_ERROR"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    SLIPPAGE_TOO_HIGH = "SLIPPAGE_TOO_HIGH"
    PRICE_DEVIATION_TOO_HIGH = "PRICE_DEVIATION_TOO_HIGH"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    DUPLICATE_EVALUATION = "DUPLICATE_EVALUATION"
    DUPLICATE_ORDER_INTENT = "DUPLICATE_ORDER_INTENT"
    ORDER_OUTCOME_UNKNOWN = "ORDER_OUTCOME_UNKNOWN"
    ORDER_TIMEOUT = "ORDER_TIMEOUT"
    ORDER_REJECTED = "ORDER_REJECTED"
    PARTIAL_FILL = "PARTIAL_FILL"
    PARTIAL_FILL_UNRESOLVED = "PARTIAL_FILL_UNRESOLVED"
    PROTECTION_FAILED = "PROTECTION_FAILED"
    TAKE_PROFIT_PLACEMENT_FAILED = "TAKE_PROFIT_PLACEMENT_FAILED"
    RECOVERY_EXHAUSTED = "RECOVERY_EXHAUSTED"
    STATE_MISMATCH = "STATE_MISMATCH"
    API_UNHEALTHY = "API_UNHEALTHY"
    JOURNAL_UNAVAILABLE = "JOURNAL_UNAVAILABLE"
    CONFIG_INVALID = "CONFIG_INVALID"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
